## VM-1
Vagrant.configure("2") do |config|

    # Configuration for scriptbox
    config.vm.define "" do |scriptbox|
      scriptbox.vm.box = "ubuntu/bionic64"
      scriptbox.vm.hostname = "scriptbox"
      scriptbox.vm.network "private_network", ip: "192.168.56.31"
    end

### VM -2

    # Configuration for web01||
    config.vm.define "web01" do |web01||
        web01.vm.box = "centos/7"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.32"
        web01.vm.provider "virtualbox" do |vb|
           vb.memory = "1024"
           vb.cpus = 2
           end
      end
