Vagrant.configure("2") do |config|

    # Configuration for scriptbox
    config.vm.define "" do |scriptbox|
      scriptbox.vm.box = "ubuntu/bionic64"
      scriptbox.vm.hostname = "scriptbox"
      scriptbox.vm.network "private_network", ip: "192.168.56.31"
    end